[package]
name = "user"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
cosmwasm-std = { version = "1.0.0", features = ["staking"] }
schemars = "0.8.0"
serde = { version = "1.0.103", features = ["derive"] }
thiserror = "1.0.24"
cw-storage-plus = "0.13.0"